name: test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Use cache
      uses: actions/cache@v1
      id: cache
      with:
        path: node_modules/
        key: ${{ hashFiles('yarn.lock') }}
    - name: install
      run: yarn
    - name: lint
      run: yarn lint
    - name: test test
      run: yarn test
